services:
  - type: web
    name: intellmeet
    runtime: image
    repo: https://github.com/palpatel1312r/intellmeet
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: base64:LspEgi4wlnV08JVOAKycsjk78tNH+brqxl/DABPYmik=
      - key: APP_URL
        value: https://intelmeet-9j1t.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        value: postgresql://intellimet_user:UIC85X1WIbytp9y5DCkqBPOTXKfS2DL9@dpg-d8ogp3km0tmc73co7oj0-a.oregon-postgres.render.com:5432/intelmeet?sslmode=require
